spring.application.name=CrowPing
server.port=${PORT}
spring.config.import=optional:file:.env[.properties]
spring.mvc.hiddenmethod.filter.enabled=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=${HIKARI_POOLSIZE}
spring.datasource.hikari.minimum-idle=${MINIDLE}
spring.datasource.hikari.connection-timeout=60000
spring.datasource.url=${CONNECTION_STRING}
spring.jpa.hibernate.ddl-auto=${DDL}
app.pinglimit=${PING_LIMIT}
app.timeout=${TIMEOUT}
app.executor.corepool=${EXECUTOR_COREPOOL}
app.executor.maxpool=${EXECUTOR_MAXPOOL}
app.executor.queuecapcity=${EXECUTOR_QUEUECAP}
app.ping.fixDelay=${EXECUTOR_FIXDELAY}
app.nthreads=${EXECUTOR_NTHREADS}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.web.error.whitelabel.enabled=false
app.baseurl=${BASEURL}
app.myemail=${MY_EMAIL}